# Generated by Django 3.2.15 on 2022-08-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='amount',
        ),
        migrations.AddField(
            model_name='sales',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='buyying_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
