# Generated by Django 3.2.15 on 2022-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_stock_created_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_ad',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
